/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna.UI;
import hattmakarna.data.Customer;
import hattmakarna.data.EmailOrPhone;
import static hattmakarna.util.Validerare.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author james
 */

public class AddPhoneEmailWindow extends javax.swing.JFrame {

    private EmailOrPhone emailOrPhone;
    private Customer aCustomer;
    private EditCustomer previousWindow;
    
    
    
    /**
     * Creates new form addPhoneEmailWindow
     */
    public AddPhoneEmailWindow(Customer aCustomer, EmailOrPhone value, 
            EditCustomer previousWindow) {
        initComponents();
        emailOrPhone = value;
        this.aCustomer = aCustomer;
        this.previousWindow = previousWindow;
        
        lblAddError.setVisible(false);
        btnAdd.setEnabled(false);
        
        setLocationRelativeTo(null);
        
        if(emailOrPhone == emailOrPhone.EMAIL){
            this.setTitle(aCustomer.getFullName() + " - Lägg till email");
            lblAdd.setText("Ange emailadress: ");
        }
        else if(emailOrPhone == emailOrPhone.PHONE){
            this.setTitle(aCustomer.getFullName() + " - Lägg till telefonnummer");
            lblAdd.setText("Ange telefonnummer: ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdd = new javax.swing.JLabel();
        tfAdd = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblAddError = new javax.swing.JLabel();

        lblAdd.setText("jLabel1");

        tfAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAddKeyReleased(evt);
            }
        });

        btnAdd.setText("Lägg till");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblAddError.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdd)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddError))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(lblAddError))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        switch(emailOrPhone){
            case EMAIL:
            {
                if(!validateEmail(tfAdd.getText())){
                    lblAddError.setText("Emailadress ogilitig!");
                    lblAddError.setVisible(true);
                }
                else{
                    aCustomer.addEmailAdress(tfAdd.getText());
                    previousWindow.getModel(EmailOrPhone.EMAIL).addElement(tfAdd.getText());
                    previousWindow.getSaveButton().setEnabled(true);
                    this.setVisible(false);
                }
                break;
            }
            case PHONE:
            {
                if(!validatePhoneNumber(tfAdd.getText())){
                    //Valideraren släpper igenom nummer med fler siffror än 10
                    lblAddError.setText("Telefonnummer ogilitigt!");
                    lblAddError.setVisible(true);
                }
                else{
                    aCustomer.addTelephoneNumber(tfAdd.getText());
                    previousWindow.getModel(EmailOrPhone.PHONE).addElement(tfAdd.getText());
                    previousWindow.getSaveButton().setEnabled(true);
                    this.setVisible(false);
                }
            }
            break;
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tfAddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAddKeyReleased
        if(!tfAdd.getText().isEmpty() && evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnAdd.doClick();
        }
        
        if(tfAdd.getText().isEmpty()){
            btnAdd.setEnabled(false);
        }
        else{
            btnAdd.setEnabled(true);
        }
    }//GEN-LAST:event_tfAddKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPhoneEmailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPhoneEmailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPhoneEmailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPhoneEmailWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new addPhoneEmailWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAddError;
    private javax.swing.JTextField tfAdd;
    // End of variables declaration//GEN-END:variables
}
