/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna.UI;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import hattmakarna.data.User;
import hattmakarna.util.PrintDebugger;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author james
 */
public class ChangePassWindow extends javax.swing.JFrame {

    private User loggedIn;
    private boolean saveOK;
    
    public ChangePassWindow(User loggedIn) {
        initComponents();
        
        this.loggedIn = loggedIn;
        
        this.setTitle("Ändra lösenord");
        this.setLocationRelativeTo(null);
        lblOldPWError.setVisible(false);
        lblNewPWError.setVisible(false);
        lblPwChanged.setVisible(false);
        lblEmptyError.setVisible(false);
        
        
        //Textfields listener
        DocumentListener oldPwDl = new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { update(); }
            public void removeUpdate(DocumentEvent e) { update(); }
            public void changedUpdate(DocumentEvent e) { }
            
            private void update() {
                checkFields();
                // Hide errors on any input
                lblOldPWError.setVisible(false);
                lblPwChanged.setVisible(false);
                lblEmptyError.setVisible(false);
            }
            
        };
        
        DocumentListener newPWDl = new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { update(); }
            public void removeUpdate(DocumentEvent e) { update(); }
            public void changedUpdate(DocumentEvent e) { }
            
            private void update() {
                checkFields();
                // Hide errors on any input
                lblNewPWError.setVisible(false);
                lblPwChanged.setVisible(false);
                lblEmptyError.setVisible(false);
            }
            
        };

        pwOld.getDocument().addDocumentListener(oldPwDl);
        pwNew.getDocument().addDocumentListener(newPWDl);
        pwNewAgain.getDocument().addDocumentListener(newPWDl);
        
        
        //'Enter'-key shortcut
        getRootPane().setDefaultButton(null);
        InputMap im = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        ActionMap am = getRootPane().getActionMap();

        im.put(KeyStroke.getKeyStroke("ENTER"), "trySave");
        am.put("trySave", new AbstractAction() 
        {    
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (btnSave.isEnabled()) {
                    btnSave.doClick();
                }
                else{
                    lblEmptyError.setVisible(true);
                    Toolkit.getDefaultToolkit().beep();
                }
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        pwOld = new javax.swing.JPasswordField();
        lblOldPWError = new javax.swing.JLabel();
        lblOldPW = new javax.swing.JLabel();
        pwNew = new javax.swing.JPasswordField();
        lblNewPW = new javax.swing.JLabel();
        lblNewPWError = new javax.swing.JLabel();
        pwNewAgain = new javax.swing.JPasswordField();
        lblNewPWAgain = new javax.swing.JLabel();
        lblPwChanged = new javax.swing.JLabel();
        lblEmptyError = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(330, 230));
        setResizable(false);

        btnBack.setText("Tillbaka");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        btnSave.setText("Spara");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblOldPWError.setForeground(new java.awt.Color(255, 0, 51));
        lblOldPWError.setText("Fel lösenord!");
        lblOldPWError.setPreferredSize(new java.awt.Dimension(65, 10));

        lblOldPW.setText("Gamla lösenordet:");

        lblNewPW.setText("Nya lösenordet:");

        lblNewPWError.setForeground(new java.awt.Color(255, 0, 51));
        lblNewPWError.setText("Lösenorden måste matcha!");
        lblNewPWError.setPreferredSize(new java.awt.Dimension(143, 10));

        lblNewPWAgain.setText("Nya lösnordet igen:");

        lblPwChanged.setText("Lösenord ändrat!");

        lblEmptyError.setForeground(new java.awt.Color(255, 0, 51));
        lblEmptyError.setText("Inget fält får vara tomt!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNewPWAgain)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pwNewAgain, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblOldPWError, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOldPW)
                                    .addComponent(lblNewPW)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pwNew, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(pwOld)))
                        .addComponent(lblNewPWError, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPwChanged)
                        .addGap(25, 25, 25)
                        .addComponent(lblEmptyError)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOldPW)
                    .addComponent(pwOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lblOldPWError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPW)
                    .addComponent(pwNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNewPWError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewPWAgain)
                    .addComponent(pwNewAgain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwChanged)
                    .addComponent(lblEmptyError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveOK = true;
        
        String oldPw = new String(pwOld.getPassword());
        String newPw = new String(pwNew.getPassword());
        String newPwAgain = new String(pwNewAgain.getPassword());
        
        if(!oldPw.equals(loggedIn.fetchCurrentPW())){
            lblOldPWError.setVisible(true);
            saveOK = false;
        }
        
        if(!newPw.equals(newPwAgain)){
            lblNewPWError.setVisible(true);
            saveOK = false;
        }        
        
        if(saveOK){
            lblPwChanged.setVisible(true);
            loggedIn.setPWCandidate(newPw);
            loggedIn.savePW();
            PrintDebugger.info("Här savear man till DB då, men inte just nu");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        //Tillbaka till förra fönstret
    }//GEN-LAST:event_btnBackMouseClicked

    private void checkFields() {
        boolean allFilled = pwOld.getPassword().length != 0
        && pwNewAgain.getPassword().length != 0
        && pwNew.getPassword().length != 0;

        btnSave.setEnabled(allFilled);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ChangePassWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblEmptyError;
    private javax.swing.JLabel lblNewPW;
    private javax.swing.JLabel lblNewPWAgain;
    private javax.swing.JLabel lblNewPWError;
    private javax.swing.JLabel lblOldPW;
    private javax.swing.JLabel lblOldPWError;
    private javax.swing.JLabel lblPwChanged;
    private javax.swing.JPasswordField pwNew;
    private javax.swing.JPasswordField pwNewAgain;
    private javax.swing.JPasswordField pwOld;
    // End of variables declaration//GEN-END:variables
}
