/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hattmakarna.UI;
import hattmakarna.UI.OrderWindow;
import hattmakarna.data.Customer;
import hattmakarna.data.User;
import static hattmakarna.data.Hattmakarna.idb;
import oru.inf.InfException;
import hattmakarna.data.Model;
import hattmakarna.data.HatRegister;
import hattmakarna.data.ModelRegister;
import hattmakarna.data.Hat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import java.util.*; 
/**
 *
 * @author joelf
 */
public class HattWindow extends javax.swing.JFrame {
private Model model;
private HatRegister hatRegister;
private ModelRegister modelRegister;
 private User userLoggedIn;

    /**
     * Creates new form HattWindow
     */

    public HattWindow(User userLoggedIn,Model model) {

  
        this.userLoggedIn = userLoggedIn;
        this.model = null;
        this.modelRegister = new ModelRegister();
        this.hatRegister = new HatRegister(idb);
        initComponents();
        fillTable();
    }
    public HattWindow(User userLoggedIn){

        

        this.userLoggedIn = userLoggedIn;

        this.model = null;
        this.modelRegister = new ModelRegister(idb);
        this.hatRegister = new HatRegister(idb);
        initComponents();
        fillTable();

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRedigering = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Lagerförda Hattar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Namn", "Pris", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnRedigering.setText("Redigera");
        btnRedigering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeringActionPerformed(evt);
            }
        });

        btnBack.setText("Tillbaka");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAdd.setText("Lägg till");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRedigering)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRedigering)
                    .addComponent(btnAdd))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRedigeringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeringActionPerformed

         int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Välj en hatt i tabellen först.");
        return;
    }

    String model_id = jTable1.getValueAt(selectedRow, 0).toString(); // Hämta från kolumn 0 (ID)

    Model selectedModel = modelRegister.getModel(model_id);
    if (selectedModel != null) {
        this.setVisible(false);
        this.dispose();
        EditHat editWindow = new EditHat(userLoggedIn, selectedModel);
        editWindow.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Kunden kunde inte hittas.");
    }
    }//GEN-LAST:event_btnRedigeringActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

       try {
        new MainMenu(userLoggedIn).setVisible(true);
        this.dispose();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Ett fel inträffade när vi försökte gå tillbaka till huvudmenyn.");
    
}


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
this.setVisible(false);
        this.dispose();
        AddHatWindow AddHatWindow = new AddHatWindow(userLoggedIn);
        AddHatWindow.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed
    private void fillTable() {
      
   System.out.println("fillTable körs");

    // Hämta alla hattar och alla modeller
    ArrayList<Model> models = modelRegister.getAllHats();
    ArrayList<Hat> hats = hatRegister.getAllHats();

    // Skapa en lista för de modeller som vi ska visa
    List<Model> filteredModels = new ArrayList<>();

    // Filtrera bort hattar med namn "special"
    

        // Gå igenom varje hatt och kontrollera om namnet är "special"
        for (Model model : models) {
            if (!model.getName().equalsIgnoreCase("special")) {
                filteredModels.add(model);
            }
        }

        
      
  
    

    // Skapa tabellens data och uppdatera den
    String[] columnNames = {"model_id", "Namn", "Pris"};
    Object[][] data = new Object[filteredModels.size()][3];
    for (int i = 0; i < filteredModels.size(); i++) {
        Model m = filteredModels.get(i);
        data[i][0] = m.getModelID();
        data[i][1] = m.getName();
        data[i][2] = m.getPrice();
    }

    javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(data, columnNames) {
        public boolean isCellEditable(int row, int column) {
            return false; // Gör tabellen inte redigerbar
        }
    };

    jTable1.setModel(tableModel);
    jTable1.getColumnModel().getColumn(0).setMinWidth(0);
    jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    jTable1.getColumnModel().getColumn(0).setWidth(0);

    // Lägg till MouseListener för att hantera dubbelklick
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) {
                // Enkelklick eller dubbelklick
                String modelId = (String) jTable1.getValueAt(selectedRow, 0);
                
                // Dubbelklick (vid event.getClickCount() == 2)
                if (evt.getClickCount() == 2) {
                    dispose();
                    openEditCustomerWindow(modelId); // Öppnar redigeringsfönstret
                }
            }
        }
    });

}
    private void openEditCustomerWindow(String model_id) {
    Model selectedModel = modelRegister.getModel(model_id);
    if (selectedModel != null) {
       EditHat editWindow = new EditHat(userLoggedIn, selectedModel);
        editWindow.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Kunden kunde inte hittas.");
    }
}

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //try {
           // for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //if ("Nimbus".equals(info.getName())) {
                  //  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  //  break;
               // }
           // }
       // } catch (ClassNotFoundException ex) {
          //  java.util.logging.Logger.getLogger(HattWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       // } catch (InstantiationException ex) {
           // java.util.logging.Logger.getLogger(HattWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       // } catch (IllegalAccessException ex) {
           // java.util.logging.Logger.getLogger(HattWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (javax.swing.UnsupportedLookAndFeelException ex) {
           // java.util.logging.Logger.getLogger(HattWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       // }
        //</editor-fold>

        /* Create and display the form */
       // java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new HattWindow().setVisible(true);
           // }
       // });
   // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRedigering;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
